#
# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return
PS1='[\u@\h \W]\$ '

# if command -v nu &> /dev/null; then 
#   exec nu 
# fi

if [[ -z "$ZELLIJ" ]]; then
  zellij
fi
